# Generated by Django 3.2.14 on 2022-08-01 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sampling_file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_gp', models.CharField(max_length=250)),
                ('count_top_gp', models.IntegerField()),
                ('top_ip', models.CharField(max_length=250)),
                ('count_top_ip', models.IntegerField()),
                ('top_mac', models.CharField(max_length=250)),
                ('count_top_mac', models.IntegerField()),
                ('top_problems', models.CharField(max_length=250)),
                ('count_top_problems', models.IntegerField()),
                ('file_incidendy', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='data_sampling_file.statiskincidents')),
            ],
        ),
    ]
