# Generated by Django 3.2.14 on 2022-08-01 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_sampling_file', '0002_topdatafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topdatafile',
            name='file_incidendy',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='file_incidendys', to='data_sampling_file.statiskincidents'),
        ),
    ]
